print("ПОДЗЕМЕЛЬЕ: ТИХИЙ КОЛОДЕЦ")
print("Как зовут героя?")
name = input()
print(f"Добро пожаловать, {name}!")
print("Ты входишь в подземелье. Здесь темно и пахнет сыростью.")
print("Настройка героя.")
print("Здоровье, сила, ловкость, выносливость по одному числу в строке:")
health = int(input())
strength = int(input())
agility = int(input())
endurance = int(input())

base_attack = 10
damage = base_attack + strength * 1.5
crit_damage = damage * 2
stamina = (health + endurance) // 10

print("Характеристики героя:")
print(f"Здоровье:     {health}")
print(f"Сила:         {strength}")
print(f"Ловкость:     {agility}")
print(f"Выносливость: {endurance}")
print()
print(f"Урон героя:       {damage:.1f}")
print(f"Критический урон: {crit_damage:.1f}")
print(f"Запас сил:        {stamina}")
print()
print("Что делаешь?")
print("1")
print("осмотреться")
print("2")
print("идти вперёд")
print("3")
print("отдохнуть")
print("4")
print("прислушаться")
print("5")
print("зажечь факел")
action = input()
print(f"Удачи, {name}!")
